repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        language: system
        entry: pnpm exec prettier --check
        files: \.(ts|js|vue|json|md|ya?ml|css)$
        exclude: ^(pnpm-lock\.yaml|LICENSE|CHANGELOG\.md)$

      - id: eslint
        name: ESLint
        language: system
        entry: pnpm exec eslint
        files: \.(ts|vue|js)$

      - id: stylelint
        name: Stylelint
        language: system
        entry: pnpm exec stylelint --allow-empty-input
        files: \.(css|vue)$

      - id: typecheck
        name: Typecheck
        language: system
        entry: pnpm typecheck
        pass_filenames: false
        stages: [pre-push]

      - id: vitest
        name: Vitest
        language: system
        entry: pnpm test
        pass_filenames: false
        stages: [pre-push]
